### ISSUE TITLE
Is it possible to exclude files from the result

### ISSUE THREAD

**Issue by astoilkov** [szwacz/fs-jetpack#10]

**Comment by astoilkov** [comment]
Using `jetpack.find` with the `matching` key I could include options. Is there a way to exclude some of the results. I tried using a excluding pattern but without success.
```javascript
jetpack.find('./tmp/app', {
    matching: ['**/*.js', '!node_modules/**/*.js']
  })
```

**Comment by szwacz** [comment]
Exclusion with exclamation mark works, but paths are anchored to CWD, so your path should probably look like `!./tmp/app/node_modules/**`. Does it work this way?

**Comment by astoilkov** [comment]
Yes it works. However, this sound a bit strange. I thought the first parameter for find is exactly the base from where to find...like a cwd for the function. Why you have chosen for the method to work this way?

**Comment by szwacz** [comment]
Ahhh, I don't remember API I coded myself :). Ok, it works this way (and probably isn't explained in docs clear enough):
```js
jetpack.find('./tmp/app', {
  matching: [
    '**/*.js', 
    '!tmp/app/node_modules/**/*.js', // This syntax should be anchored to CWD
    '!./node_modules/**/*.js' // This syntax (use of dot) ahould be anchored to directory you are finding in
    // So both of lines above should have the same effect.
  ]
});
```
How about this?

**Comment by astoilkov** [comment]
Ahaaa. This is awesome. However, doesn't this mean that the `**/*.js` should work the same way. I mean:
```javascript
jetpack.find('./tmp/app', {
  matching: [
    // note the ./ here
    './**/*.js', 
    '!tmp/app/node_modules/**/*.js', // This syntax should be anchored to CWD
    '!./node_modules/**/*.js' // This syntax (use of dot) ahould be anchored to directory you are finding in
    // So both of lines above should have the same effect.
  ]
});
```

**Comment by szwacz** [comment]
I believe `./**/*.js` works the same way. If it's not it is a bug :)

**Comment by astoilkov** [comment]
I meant to say something else. Currently there is no different between `./**/*.js` and `**/*.js`. However, for `./node_modules/**/*.js` and `node_modules/**/*.js` there is. Don't you think this is inconsistent?

**Comment by szwacz** [comment]
Now I see what you mean. But why call it inconsistent? You just have edge case of two patterns which gives the same result.

**Comment by astoilkov** [comment]
Yeah. But with the logic of `node_modules/**/*.js` returning all js files regarding to the current `cwd` path then `**/*.js` also should do the same. So the patters for those two perform differently.

**Comment by szwacz** [comment]
Sorry, but I really don't get it. Can you show me on example what you mean?

`**/*.js` is anchored to CWD, `./**/*.js` is anchored to directory we are finding in, but selector `**` matches as many dirs in chain as there is, so both return the same result. Where is the catch?

**Comment by astoilkov** [comment]
Aha OK. So there is a bug. Get this file structure:
```
folder1
    file2.js
    file3.js
file1.js
code.js
```

In `code.js` we have:

```
jetpack.find('./folder', {
  matching: [
    // this correctly returns file2.js and file3.js
    './**/*.js',
  ]
});
```

However, if I do:

```
jetpack.find('./folder', {
  matching: [
    // this incorrectly returns file2.js and file3.js only
    // I thought it should also return file1.js and code.js
    '**/*.js',
  ]
});
```

**Comment by szwacz** [comment]
Ok, that's something! But, now I started wondering if I really didn't overengineered it. Must rethink the whole anchoring in matchers. Maybe I can make it fly the way you expecting it to work when you opened this ticket.

Will respond soon.

**Comment by szwacz** [comment]
There is new version 0.7.0 which has been simplified. Now all globs are anchored to directory you want to find in (the same change applied to `copy()`).
Please test it now :)

**Comment by astoilkov** [comment]
Sorry for the late response. This is great. I have tried and it works like charm.

Thanks!
