### ISSUE TITLE
empty directory method?

### ISSUE THREAD

**Issue by gutenye** [szwacz/fs-jetpack#105]
Right now I use below for empty a directory:

```js
fs.list('/tmp/a')?.forEach(v => fs.remove(`/tmp/a/${v}`))
```

Is there a sugar method like `fs.emptyDir(path)` exist? Thanks

**Comment by szwacz** [comment]
There is:
```js
jetpack.dir("some_dir", { empty: true });
```
I was thinking many times about something better, maybe finally will do just `jetpack.empty()`...

**Comment by gutenye** [comment]
@szwacz Awesome, thank you very much!
