### ISSUE TITLE
Support creation time 

### ISSUE THREAD

**Issue by adamperrry** [szwacz/fs-jetpack#109]
Right now, only `mtime`, `ctime`, and `atime` are returned when `{ times: true } `is set. It would be awesome to be able to include creation time in that as well.

**Comment by szwacz** [comment]
So you mean the `birthtime` property? I don't know why it's not supported, because there is no reason not to be :) Will look into it in free time.

**Comment by szwacz** [comment]
Added. Version 5.0.0 supports `birthTime` property.
