### ISSUE TITLE
In the function  findAsync , property  filter and absolutePath is unfriend

### ISSUE THREAD

**Issue by AutismPatient** [szwacz/fs-jetpack#111]
![image](https://user-images.githubusercontent.com/37021551/196336393-72a608c9-0df3-4123-a03e-5f22f9873963.png)
[comparison](javascript:;)
![image](https://user-images.githubusercontent.com/37021551/196336443-7fc8d00e-5127-4ce1-a657-fcbea45b0326.png)

**Comment by AutismPatient** [comment]
I need this absolutePath to filter

**Comment by AutismPatient** [comment]
I need to implement the exclusion of files inside the hidden directory

**Comment by szwacz** [comment]
I'm sorry but I don't understand. You would need to describe the problem with more context and also I hope this is not a automatic translation issue :)

**Comment by AutismPatient** [comment]
Sorry, no hidden directory related parameter Settings are provided at this time

**Comment by AutismPatient** [comment]
Hidden directory files will not be culled

**Comment by papb** [comment]
Do you want to ignore hidden directories with `findAsync`?

By hidden, do you mean names starting with `.`?

**Comment by AutismPatient** [comment]
> 你想忽略隐藏目录`findAsync`吗？
> 
> 隐藏，您是指以 开头的名称`.`吗？

Yes, I wish I could add an option   **Whether to skip the hidden directory**

- This operation must be enabled during the retrieval phase

**Comment by szwacz** [comment]
On Windows there is no easy way to say if file is hidden in node.js, because Windows supports hidden files differently than unix-family operating systems. Here is some library that does this with extra native code: https://www.npmjs.com/package/is-hidden-file 

On unix systems I believe this is as easy as check if the file name starts with `.` (dot).

**Comment by AutismPatient** [comment]
Thank you for your answer

**I just want to filter out the hidden files during the retrieval phase**

- However, the filter argument does not return the path, it only returns the filename, which makes it impossible to get the full path to determine whether the file is hidden or not

**Comment by szwacz** [comment]
Ah, ok, now it finally makes sense and it's fixable in the code.

**Comment by szwacz** [comment]
Freshly published version 5.1.0 outpust also `absolutePath` in filter function.
