### ISSUE TITLE
Error: EPERM: operation not permitted, stat 'D:\System Volume Information'

### ISSUE THREAD

**Issue by AutismPatient** [szwacz/fs-jetpack#112]
include:  
![image](https://user-images.githubusercontent.com/37021551/196419046-57b2ddfb-e865-4c8d-946d-d4e27d7cd09c.png)

**Comment by papb** [comment]
Please give more context, it's impossible to help with this issue right now.

**Comment by AutismPatient** [comment]
This type of error occurs when the access directory contains some system directories
