### ISSUE TITLE
[feature request] allow reading *.jsonc files

### ISSUE THREAD

**Issue by whalemare** [szwacz/fs-jetpack#118]
It's totally like regular `.json` files, but allow comments with `//`

`example.jsonc`
```jsonc
{
  // some comment
  "field": "value"
}
```

`example.json`
```json
{
  // some comment
  "field": "value"
}
```

**Comment by szwacz** [comment]
Thank you for the request, but I'm afraid I can't agree to have this feature as part of the library.
fs-jetpack is simple, everyday utility library and I want to keep it lean and small, so want to have as little npm packages it depends on. If .jsonc was part of core node.js then sure, why not :)

You can read file via jetpack as string, and then convert it through jsonc library yourself, so this is only convenience booster. At the same time all people not using jsonc would be forced to dowload yet another npm library when they decide to use jetpack, and npm-download-bloat is something I want to fight.
