### ISSUE TITLE
Ignore dotfiles for matcher

### ISSUE THREAD

**Issue by tmerse** [szwacz/fs-jetpack#16]
I was trying to ignore the .git folder in a helper script.
Obviously, this won't work, as the '.' in itself is a reserved word when globbing.

~~~ {.javascript}
    // does not work
    matching: ['!.git/**/*']
~~~

The minimatch package provides the option `dot = true` to address this issue.

~~~ {.javascript}
    // works, but will ignore git/... and .git/...
    matching: ['!git/**/*']
~~~

Hardcoding the `dot` option into here would be a bad idea, 
https://github.com/szwacz/fs-jetpack/blob/master/lib/utils/matcher.js#L48-L49

If you agree that there is an issue, I would suggest extending the configuration object, so that a user can put in arbitrary minimatch options.

~~~ {.javascript}
var create = function (patterns, basePath, matchOpts) {
    matchOpts = matchOpts || {};
    matchOpts.matchBase = true;
    matchOpts.nocomment = true;
..
var matchers = patterns.map(function (pattern) {
        return new Minimatch(pattern, matchOpts);
    });
~~~

Calls to `copy` and `find` could be used with `options.matchOpts` than.
I could fork and pr.
What do you think?

**Comment by szwacz** [comment]
Hey there.

It looks much more like I've screwed something up. I don't think there is any reason to treat dotfiles differently than ordinary files. You said dot is a reserved word, but I can't find reasons why it should be. The `dot` option in minimatch as I read its description looks like turing on extra behaviour for 'optional dot'.

Added fast test to file https://github.com/szwacz/fs-jetpack/blob/master/spec/utils/matcher.spec.js to see what's going on:
```
fit("dot files", function () {
        var test = matcher.create('.a');
        expect(test('/foo/.a')).toBe(true);

        test = matcher.create('!.a');
        expect(test('/foo/.a')).toBe(false);
        expect(test('/foo/.b')).toBe(true);

        test = matcher.create('/*/.a/*');
        expect(test('/foo/.a/b')).toBe(true);
        expect(test('/foo/.b/c')).toBe(false);

        test = matcher.create('!/*/.a/*');
        expect(test('/foo/.a/b')).toBe(false);
        expect(test('/foo/.b/c')).toBe(true);
    });
```
And this test pases.

So probably there is a bug in logic of `copy` or `find` methods. Will look into it in incoming days, but all help is greatly appreciated :)

**Comment by szwacz** [comment]
Apparently it works already. Path which you gave here as an example `matching: ['!.git/**/*']`isn't correct. It should be `matching: ['!./.git/**/*']`. Jetpack is wired in a way that if any slash has been found in glob pattern this pattern is treated as an absolute path, if you want for it to be treated as relative add `./` at the front.

Now this absolute paths looks to me as a stupid behaviur (hence your problems). Need to rethink it.

**Comment by tmerse** [comment]
Thank you for the quick answer and providing a nice high-level abstraction of fs.

**Comment by szwacz** [comment]
No problem! So does `['!./.git/**/*']`work for you?
