### ISSUE TITLE
Possible bug in how Jetpack handles buffers

### ISSUE THREAD

**Issue by mrapczynski** [szwacz/fs-jetpack#22]
I've been fighting a madening issue loading PDFs with Jetpack only to find out it seems to have some kind of flaw when I request that a file be read into a buffer rather than with the default `utf8` encoding. 

Because Jetpack is not providing me a buffer as a I requested, when I  go to write the data to another target it seems to be getting written out in another encoding - possibly `utf8` which doubles the size and appears corrupt to the tool expecting in the input.

Below is a sample program I wrote quickly to validate the issue outside of my program. I also attached the sample data so you try it out.

```javascript
'use strict';
var FileSystem = require('fs-promise');
var Jetpack = require('fs-jetpack');
var Promise = require('bluebird');

Promise.props({
    fsPromise: FileSystem.readFile('tests/sample-plain.pdf'),
    jetpackDefault: Jetpack.readAsync('tests/sample-plain.pdf'),
    jetpackAsBuffer: Jetpack.readAsync('tests/sample-plain.pdf', 'buffer')
})
.then(results => {
    console.log(`fs-promise read ${results.fsPromise.length} bytes, buffer = ${Buffer.isBuffer(results.fsPromise)}`);
    console.log(`fs-jetpack (default) read ${results.jetpackDefault.length} bytes, buffer = ${Buffer.isBuffer(results.jetpackDefault)}`);
    console.log(`fs-jetpack (explict buffer) read ${results.jetpackAsBuffer.length} bytes, buffer = ${Buffer.isBuffer(results.jetpackAsBuffer)}`);
});
```
**Results:**
```
fs-promise read 389232 bytes, buffer = true
fs-jetpack (default) read 376554 bytes, buffer = false
fs-jetpack (explict buffer) read 376554 bytes, buffer = false
```
**Sample Attachments**
[sample-plain.pdf](https://github.com/szwacz/fs-jetpack/files/271076/sample-plain.pdf)

**Comment by szwacz** [comment]
Tested your code, definitley works for me :)
This option had a breaking change in v0.8.0. Are you sure you have latest jetpack installed?
