### ISSUE TITLE
The readSync has a bug on 0.9.0

### ISSUE THREAD

**Issue by RobotJiang** [szwacz/fs-jetpack#23]
When read a file (return as json) which is not exist, It will throw a error JSON parsing failed while reading. It should return undefined If the file does not exist.

**Comment by szwacz** [comment]
You're right this wasn't covered by tests, what I've jsut fixed: https://github.com/szwacz/fs-jetpack/commit/ef7f792d94ec8620293bdd3a9ce15489f3033bcd
But... this test passes. Could you please provide failing code snippet?

**Comment by RobotJiang** [comment]
var userDataDir    = jetpack.cwd('./');
userDataDir.read('none_exist_file', 'json');
Then throw : Error: JSON parsing failed while reading. from source code in read.js 
I look up source code, I think  the readSync function has some logic errors, your test case is not covered or not correct.
Please try : jetpack.read('nonexistent.txt','json') with second param.

 try {
    data = fs.readFileSync(path, { encoding: encoding });
  } catch (err) {
    if (err.code === 'ENOENT') {
      // If file doesn't exist return undefined instead of throwing.
      data = undefined;
    } else {
      // Otherwise rethrow the error
      throw err;
    }
  }

  try {
    if (retAs === 'json') {
      data = JSON.parse(data);
    } else if (retAs === 'jsonWithDates') {
      data = JSON.parse(data, jsonDateParser);
    }
  } catch (err) {
    throw makeNicerJsonParsingError(path, err);
  }

When the file dose not exist, the JSON.parse(undefined) will be executed, because the data is undefined.

**Comment by szwacz** [comment]
You're totally right (and boy what a moronic mistake I made in test). Bugfixed in version 0.9.1
