### ISSUE TITLE
more fs options

### ISSUE THREAD

**Issue by gbaumgart** [szwacz/fs-jetpack#26]
Hi,
do you have some plans to complete the copy & move operations for "Override if newer/Override if size differs" ? 

I gonna do this that days in a fork and just wanted to hear from you first. 

thanks,
g

**Comment by szwacz** [comment]
I'm definitelly interested.

How do you plan the API? My first thought is about string passed to `overwrite` key:
```js
jetpack.copy('from', 'to', { overwrite: 'ifNewer' }
```
```js
jetpack.copy('from', 'to', { overwrite: 'ifSizeDiffers' }
```

**Comment by gbaumgart** [comment]
that will do too. i prefer always a typed enumeration as in C, ie: enum MODE{ IF_NEWER:'if newer',...} but ok, that's optional then to use. 
will ping here if its done, closing for now. 
thanks for the heads up!
g
