### ISSUE TITLE
Optionally Disable Tree Traversal for Find Function

### ISSUE THREAD

**Issue by hawkins** [szwacz/fs-jetpack#27]
I'm using fs-jetpack in a situation in which sub-directories are too large to be explored timely. 

It would be nice to have a parameter in `find` that can be set `false` to disable tree traversal from the Find function.

One non-recursive call might look like this:

```javascript
jetpack.find({
  recursive: false
});
```

Is there any particular reason why `find` is currently always recursive?

**Comment by szwacz** [comment]
Find is now always recursive because this is the best way you can find stuff in folders ;)

May I ask what you're looking for in just one directory? Files with certain extension? Just curious.

**Comment by hawkins** [comment]
I'm looking for files with a given extension (*.bat, *.cfg, *.exe., *.js) in a top-level folder for a project. There are several thousand files here, but I'd still like to get the result as quickly as possible. If `find` explores sub-directories like node_modules, we're visiting potentially exponentially more files than we need. I know all the files I'm looking for are in the top level of the project, so I don't want to look any further below. 

If `find` is not the solution to this problem, is there a better way using fs-jetpack that you could suggest?

**Comment by szwacz** [comment]
Makes sense. Will see what I can do.

**Comment by hastebrot** [comment]
I also want to find files in the current directory only.

**Comment by szwacz** [comment]
This is currently in progress, but I need to rebuild some internals to make it possible. Some patience required.

**Comment by szwacz** [comment]
Version 0.10.0 supports this option. Please give it a try.

**Comment by hawkins** [comment]
Works great, well done! Very excited for this feature!! :smile:
