### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by ramirofages** [szwacz/fs-jetpack#28]
Hi, I wanted to ask how to handle errors in your library ( which is awesome btw). I'm currently trying to copy one file to a location, but I would like to rename the file if one already exists (e.g. if text.txt exists, then text(1).txt will be created). Is there a way to accomplish this? Cheers

**Comment by szwacz** [comment]
Hi. You can use posix error code to do that. Just let the copy task fail, and if failed then provide different name and retry.
```js
jetpack.copyAsync('a.txt', 'b.txt')
.catch(function (err) {
    if (err.code === 'EEXIST') {
        jetpack.copyAsync('a.txt', 'b (1).txt');
    }
});
```

**Comment by ramirofages** [comment]
Alright, thanks!
