### ISSUE TITLE
Recursive find directories only matches first occurence

### ISSUE THREAD

**Issue by DeeVeX** [szwacz/fs-jetpack#33]
I used the recursive **findAsync** function on version 0.9.2 where it worked just fine.
After upgrading to 0.10.2, findAsync only returns the first occurence of a match.

# Example
**Directorystructure**:
C:/foo/
C:/foo/myfolder/bar/random.txt
C:/foo/myfolder1/bar1/baz.txt
C:/foo/myfolder2/bar2/hello.txt

**Code**:
```
const mypath = "C:\\foo";

let futureDirectories = jetpack.findAsync(mypath , {
    directories: true,
    files: false,
    matching: ["bar*"]
}).then((barDirs) => {
    console.log("Directory: ", barDirs);
})
```

Now the weird part:
**Version 0.10.2:**
matches only `C:/foo/myfolder/bar/` (first occurence).
Remove the text file `C:/foo/myfolder/bar/random.txt` and findAsync matches `C:/foo/myfolder/bar/` `C:/foo/myfolder1/bar1/`

**Version 0.9.2:**
used to match `C:/foo/myfolder/bar/`, `C:/foo/myfolder1/bar1/` and `C:/foo/myfolder2/bar2/` as expected and without any problems.

Someone able to reproduce this behaviour?

**Comment by szwacz** [comment]
Indeed. Found this bug, should be fixed in version `0.10.3`.
