### ISSUE TITLE
copyAsync doesnt seem to copy all specified files

### ISSUE THREAD

**Issue by maca134** [szwacz/fs-jetpack#34]
While using jetpack.copyAsync to copy around 30mb of files, it doesnt seem to copy all files matching the glob.
Using the same options with jetpack.copy the results are as expected.

**Comment by szwacz** [comment]
Could you please try your case on version `0.10` and `0.9`. Copying algorithm was largely rewritten in `0.10`.

**Comment by szwacz** [comment]
Found it. Fixed in version `0.10.3`.
