### ISSUE TITLE
inspectTree doesnt work with symlinks

### ISSUE THREAD

**Issue by gbaumgart** [szwacz/fs-jetpack#35]
in your code you're skipping symlinks: https://github.com/szwacz/fs-jetpack/blob/master/lib/inspect_tree.js#L38

whilst  treeBranch.type is set to 'symlink'

you want a PR for this?  not sure what your intentions with options.symlink are...

**Comment by szwacz** [comment]
Hi, `inspect()` has symlink option, but `inspectTree()` doesn't. In `inspectTree()` it's just hardcoded to report symlinks and not follow them: https://github.com/szwacz/fs-jetpack/blob/master/spec/inspect_tree.spec.js#L239

I was thinking about this feature but didn't need it so far so it stays unimplemented.

**Comment by gbaumgart** [comment]
this is isn't needed by my anymore (i switched to mount -o bind because 'pkg-deb' won't take symlinks anyways). 
as for me, we can close this.
thanks for the heads up.
