### ISSUE TITLE
Find Top Level directories only

### ISSUE THREAD

**Issue by raybooysen** [szwacz/fs-jetpack#42]
Hi there

I'm trying to find directories at the top-level only,.  Imagine the following structure:

```
foo/
  bar/
     baz/
  kaz/
```

If i write the following code:

```
jetpack.find('./foo/', {matching: '*', recursive: false, directories: true, files: false });
```

then Jetpack will list out bar, bar/baz and kaz, while I expected to just see bar and kaz.

**Comment by szwacz** [comment]
Can't reproduce on provided example. Can you?
Also if I remember correctly there was a bug in this area few versions in the past. Please make also sure ou're using the latest.

**Comment by raybooysen** [comment]
Ah we're using 0.9.2, will close until I can test on latest.
