### ISSUE TITLE
list async/sync NFD unicode on osx

### ISSUE THREAD

**Issue by xblox** [szwacz/fs-jetpack#45]
hi,
I found an issue in list on osx: Darwin returns NFD bytes in readdir, but you actually want NFC formatting, especially then you send the file names to a browser.

however, I fixed this [here](https://github.com/xblox/fs/blob/master/src/list.ts#L14) by stealing the code from "VSCode" (extfs.ts). 

see https://github.com/mpv-player/mpv/issues/1492 and https://github.com/nodejs/node/issues/2165.

sorry its Typescript but you can take the js output from [here](https://github.com/xblox/fs/blob/master/build/list.js#L13)

**Comment by szwacz** [comment]
Thanks for letting me know. I wasn't aware something like NFD and NFC exists. But... should FS library convert those? Node guys state clearly that it shouldn't: https://nodejs.org/en/docs/guides/working-with-different-filesystems/#unicode-form-preservation

**Comment by xblox** [comment]
nice article, i agree. thanks too
