### ISSUE TITLE
Can't cross device move file on windows platform.

### ISSUE THREAD

**Issue by code-artisan** [szwacz/fs-jetpack#48]
I tried to use jetpack.move api to move file on windows platform, here is my code:
```js
import fs from 'fs-jetpack';

// ...
fs
.move(from, to)
.then(function (res) {
  // ...
}).catch(function(err) {
  // ...
});
```

```js
{
  Error: EXDEV: cross - device link not permitted,
  rename 'xxx/requestpipe.har' - > 'xxx/2cb5e04f-00f4-43b5-bf8e-a4d4decb7461.har'
  at Error(native) errno: -4037,
  code: 'EXDEV',
  syscall: 'rename',
  path: 'xxx/requestpipe.har',
  dest: 'xxx/2cb5e04f-00f4-43b5-bf8e-a4d4decb7461.har'
}
```

It's only worked on Mac machine. A bug?

**Comment by szwacz** [comment]
Technically this is not a bug. Move just manipulates link on hard drive and the operation makes sense only in bounds of one drive. (I think so, I'm not a filesystems expert)

For moving across devices you just need to apply more complicated algorithm: 
In case of `EXDEV` error 
1: copy the resource to new location
2: remove the resource from its original place

So you can quite easiliy implement it on your own if you really need it right now.

I certainly have to educate myself on this topic. Maybe there is a sense in implementing such feature in jetpack.

**Comment by code-artisan** [comment]
👌  Thank you.

**Comment by szwacz** [comment]
No problem. I'll leave the issue open, I need to check if I can implement it natively in jetpack.

**Comment by papb** [comment]
I suggest using [move-file](https://github.com/sindresorhus/move-file) under the hood to solve this.
