### ISSUE TITLE
npm has 1.0.0, github doesn't

### ISSUE THREAD

**Issue by black-snow** [szwacz/fs-jetpack#51]
Guess there's a *Release* missing on github. I have *fs-jetpack* @ 1.0.0 in my deps but `npm update` leaves me with a `fs-jetpack@1.0.0 invalid`.
[npm has the 1.0.0](https://www.npmjs.com/package/fs-jetpack)

**Comment by szwacz** [comment]
npm doesn't rely on github for version tagging, does it itself. Everything looks good on my machine. Could you please try `npm install --save fs-jetpack@latest`? I always used `npm update` to update the whole project to highest versions, which still satisfies version epressions in package.json.

**Comment by black-snow** [comment]
`npm install --save fs-jetpack@latest` adds `1.0.0` to the package.json and also seems to download the right version. Still the output is `-- fs-jetpack@1.0.0  invalid`

Well, gonna close the issue for it's actually working. Gonna change the title ad leave this here for anyone stumbling upon it. Thanks
