### ISSUE TITLE
Mac sandbox violation on creating a file with the atomic option

### ISSUE THREAD

**Issue by chryb** [szwacz/fs-jetpack#56]
The user only has permission to create files which are allowed from the dialog window. However, it resolves an error when a temporary file is created.

There aren't any solutions in my mind for this problem. I just want to mention it.

**Comment by szwacz** [comment]
I don't fully follow. I guess we're talking here about macOS app which runs in sandbox mode. `jetpack.write('foo.txt', 'bar')` will first create file `foo.txt.__new__` and then rename it to `foo.txt`. Which of those operations fail?

**Comment by chryb** [comment]
The creation of `foo.txt.__new__` because the app only has permission for files which the user has added in the dialog window. For example, the user uses the filename `foo.txt` it's a sandbox violation to create the file `foo.txt.__new__`.

**Comment by szwacz** [comment]
Hmm, so I don't think something can be done here, because the whole trick in atomic write is that you don't touch the original file, until you have fully written, new version of the file on disk (under different name). So I'm afraid atomic write just can't be used in this scenario.

**Comment by chryb** [comment]
Yes, I thought so. I just wanted to notice it because it could be easier for others if they come up with the same issue.
