### ISSUE TITLE
App crush if fs-jetpack cant follow path

### ISSUE THREAD

**Issue by godlatro** [szwacz/fs-jetpack#57]
On windows platform with electron

If I try **create** or **remove** or **read** or check **exist**  file on **lan** path "\\192.168.1.2\path\file.txt", and if PC _dont have access_ to this path - app crush with error `C:\Users\tester\Desktop\dist\win-ia32-unpacked\resources\app.asar\node_modules\fs-jetpack\lib\exist…:26 Uncaught Error: UNKNOWN: unknown error, stat`
or any like this
Better if fs-jetpack will be not crush if cant access to file or path

sorry for my english

**Comment by szwacz** [comment]
By "crush" you mean the whole electron app has crushed, or just that the error was thrown? If the first option, then have you tried to catch the error?

**Comment by godlatro** [comment]
sorry about termonology, i mean error in console, that stop every scripts,
and app not working

2017-09-13 21:12 GMT+03:00 Jakub Szwacz <notifications@github.com>:

**Comment by szwacz** [comment]
I don't follow. This is not a case from which fs-jetpack can recover, so the error need to be thrown. You should just `try/catch` the error in your code.
