### ISSUE TITLE
Alias vanilla fs methods

### ISSUE THREAD

**Issue by nikolay-borzov** [szwacz/fs-jetpack#58]
Would be convenient.
To avoid conflicts we can namespace them like this:
```
const jetpack= require('fs-jetpack');
jetpack.fs.truncate('my_file.txt', 0, ()=> {});
```

**Comment by szwacz** [comment]
The big idea here is not to expose `fs`, and instead take effort to think of better API for each `fs` feature. So I'd rather encourage you to file an feature request, and we'll see what we can do :)
