### ISSUE TITLE
Replacing pathname with var/const/__dirname

### ISSUE THREAD

**Issue by rossmuego** [szwacz/fs-jetpack#60]
I'm attempting to package an electron app that has implemented fs-jetpack, however it does not seem to be picking up pathnames that include '__dirname' or a substituted variable as a path? Is this a bug or not an implemented feature? How can I get this to work when my app has been packaged?

**Comment by szwacz** [comment]
Some snippet of code please?

**Comment by rossmuego** [comment]
For example; 

```js
const data = jetpack.read(__dirname+'/db/coins.json', json)
```

will return undefined even though there is a file in that location.

The same happens when I do this;

```js
var coinString = __dirname+'/db/coins.json'

const data = jetpack.read(coinString, json)
```

When I use this however;

```js
const data = jetpack.read('/db/coins.json', json)
```

the file is found and read successfully.

**Comment by szwacz** [comment]
So you're just combining the path to read with `__dirname`, it has nothing to do with fs-jetpack per se, it all depends how Electron supports the `__dirname` feature.
Do just `console.log(__dirname)` and see what you get. Also there should be some info on this in Electron docs.

Anyway, there is nothing I can do here regarding fixing it in fs-jetpack :)
