### ISSUE TITLE
Copy file with deeper overwrite comparison

### ISSUE THREAD

**Issue by mwpowellhtx** [szwacz/fs-jetpack#61]
I need a way to compare two binary files during the ``copy`` operation, beyond simple ``modifiedTime``, as this would most likely always be ``true`` given my approach. It seems as though potentially ``checksum`` might be the best possible approach. Can you provide a couple of examples how to do this using your module, please? Thanks!

**Comment by mwpowellhtx** [comment]
Best guess, only ``overwrite`` and ``matching`` arguments are supported via ``options``. Could ``checksum`` be added as well? As far as I can determine, the algorithms are already supported via the ``Inspect`` module, so it would be a simple matter. Thanks you!

**Comment by szwacz** [comment]
Well, not that simple. To count a checksum you need to read **both** files, then decide if copy or not, and read the source file second time to actually copy it. This is very taxing operation and can't be part of the standard copy procedure. I'll think about how to solve it.

**Comment by mwpowellhtx** [comment]
@szwacz Thanks for taking a look at that.

I figured that the info for either file was being compiled, and that each checksum could be calculated as such. Additionally counting that the hooks appear to basically be there but for enabling them, i.e. via validation hooks.

If it helps, we're talking about package sized byte size chunks, so to speak, not text file small, but not media binary large, either. Mostly tarballs, etc. At least for my purposes.

I just need something practical that I can reasonably use to determine whether the file has really changed, not necessarily that modified time is the case, as my packaging tasks "just run" always, but the checksums may change, or not.

Thanks again.

**Comment by szwacz** [comment]
The info for file is produced by "fs.stat", what gives you only metadata of the file, but gives it really quick. If the `cheksum` option of `inspect()` method is set, then inspect takes different path and reads the whole file to read the checksum.

For now there feels for me like there is really easy solution. This should work: `{ overwrtie: () => new Promise() }`. So the overwrite function should wait if promise was returned. That enables everyone to do as much computation as needed to determine if file should be copied. This is the solution I see without any deeper thinking done. Suspect to change ;)

**Comment by mwpowellhtx** [comment]
@szwacz Yessir, I did start with an overwrite callback, although I didn't provide a Promise. I'll stay tuned for more details. I understand, checksum would be a whitebox look at the file(s) involved.

**Comment by szwacz** [comment]
Done. The most elastic solution for broad set of cases is to wait for promise in `overwrite` function to resolve. Actually this worked already :D Because of promise chaining. So I only documented the feature and added test for it. Version 1.3.0 just was published.
