### ISSUE TITLE
ExperimentalWarning The fs.promises API is experimental

### ISSUE THREAD

**Issue by SpudNyk** [szwacz/fs-jetpack#67]
In node 10.1.0 performing `require('fs-jetpack')` will issue an experimental warning.

**Comment by szwacz** [comment]
There is a bullet: `vm: move emitExperimentalWarning (Daniel Bevenius) #20593` in https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#2018-05-23-version-1020-current-mylesborins
So I'm assuming this was a node's problem.
