### ISSUE TITLE
copyAsync not working on Windows 10

### ISSUE THREAD

**Issue by maca134** [szwacz/fs-jetpack#68]
No errors, script just stops before the console.log
```
const jetpack = require('fs-jetpack');
(async () => {
	await jetpack.writeAsync('test.txt',' blah blah');
	await jetpack.copyAsync('test.txt', 'test1.txt');
	console.log('done');
})();
```

Windows 10 Pro
Node v10.5.0

If you need any info, im happy to provide.

**Comment by szwacz** [comment]
I've copy pasted your snippet to VM running Windows 10 and it definitely works.

I'm sorry, but it looks more like a misconfiguration on your machine. If something so essential haven't been working I would have had a storm of issues posted here :)
