### ISSUE TITLE
inspectTree with checksum option - many files open at once when they shouldn't be

### ISSUE THREAD

**Issue by metabench** [szwacz/fs-jetpack#71]
A few minutes ago I started an inspectTree call, getting sha256 checksums, on a multi-GB file path. While I expected it to be slow, I did not expect it to open a VERY large number of files at once.

It would be nice to be able to set the number of parallel file reads, or have a reasonably low default such as 4.

Possibly outside the scope of this project, I suggest using an Observable to return tree results as they come in, or at least having that option.

**Comment by szwacz** [comment]
Fixed in v4.0.1

I've just hardcoded arbitrary number of 5 maximum concurrent reads. This is easy to parametrize, but I didn't see such necessity now.
