### ISSUE TITLE
Matcher is case sensitive on Windows systems

### ISSUE THREAD

**Issue by matortheeternal** [szwacz/fs-jetpack#73]
## Problem
When using `jetpack.copy` or `jetpack.find`, the `utils/matcher` is used to match file paths against a glob expression via `minimatch`.  On Windows systems, the expression is case sensitive even though the Windows filesystem is case insensitive.  This causes files to be excluded when it would be preferable to include them.

## Proposed Solution
Add an option `ignoreCase` to these functions which gets pased to `matcher.create`, where it gets passed to the Minimatch constructor as the `nocase` option.  Default the option to true on Windows systems.

I can make a PR if desired.

**Comment by szwacz** [comment]
Hi @matortheeternal,

Your solution for the problem seems very sensible, a PR would be welcome :)

**Comment by szwacz** [comment]
Resolved in `v2.2.0`.
