### ISSUE TITLE
Jetpack.inspect limits file sizes

### ISSUE THREAD

**Issue by EddySum** [szwacz/fs-jetpack#76]
This issue is regarding a jetpack.inspect call for a file with a big size.  The function causes an error to be thrown reading "RangeError: "size" argument must not be larger than 2147483647". I believe this is a JS error for when a number is set to overflow the range. Would it be possible to have the 'size' variable be handled by a big number library. I would love to contribute in implementing this feature.

**Comment by EddySum** [comment]
Thanks for responding!

The file i was inspecting was 3.85 GB (4,141,879,576 bytes).  The number 247483647 is normally the limit for signed 32 bit numbers. It seems that something is throwing the error because the file size goes over that limit. Although, it is not js itself. 

I did try fs.stat() which was able to return the stats normally without error. The size in fs.stat() returned 4,141,879,576 as expected. 

Some function seems to be doing incorrect range checking in the jet pack? i will try to investigate this.

**Comment by papb** [comment]
Is this problem still happening?

**Comment by szwacz** [comment]
Did quck test on macOS with 6GB file and everything seems to be fine. Closing.
