### ISSUE TITLE
ENOTDIR exception in exists()

### ISSUE THREAD

**Issue by carlosperate** [szwacz/fs-jetpack#8]
Hi,

I'm using fs-jetpack v0.6.4 as part of the electron-boilerplate. I'm currently experiencing the following problem when I build a Linux executable (built on Ubuntu 12.04 server, run on 15.04 LXDE):
 
```
Uncaught Exception:
Error: ENOTDIR: not a directory, stat '/home/zeroneo/Downloads/ardublockly_64bit_2015-06-19_01.15.40/arduexec/ardublockly/index.html'
    at Error (native)
    at fs.statSync (fs.js:851:18)
    at Object.fs.statSync (ATOM_SHELL_ASAR.js:224:16)
    at Object.sync (/home/zeroneo/Downloads/ardublockly_64bit_2015-06-19_01.15.40/arduexec/resources/app.asar/node_modules/fs-jetpack/lib/exists.js:14:23)
    at Object.exists (/home/zeroneo/Downloads/ardublockly_64bit_2015-06-19_01.15.40/arduexec/resources/app.asar/node_modules/fs-jetpack/lib/jetpack.js:102:27)
    at getServerExecLocation (/home/zeroneo/Downloads/ardublockly_64bit_2015-06-19_01.15.40/arduexec/resources/app.asar/servermgr.js:38:25)
    at Object.module.exports.startServer (/home/zeroneo/Downloads/ardublockly_64bit_2015-06-19_01.15.40/arduexec/resources/app.asar/servermgr.js:85:34)
    at EventEmitter.<anonymous> (/home/zeroneo/Downloads/ardublockly_64bit_2015-06-19_01.15.40/arduexec/resources/app.asar/main.js:62:12)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
```

As pexpected from the error message, the line from my code is using the `exist` function to a file that does not exist `home/zeroneo/Downloads/ardublockly_64bit_2015-06-19_01.15.40/arduexec/ardublockly/index.html`:
```
if (jetpack.exists(
                    ardublocklyRootDir.path('ardublockly') + '/index.html')) {

```

And the line in the jetpack library calls `fs.statSync`:
```
try {
   var stat = fs.statSync(path);
...
```
The try statement only filters the `ENOENT` exception, and throws any other.

The build server uses node 0.10.33

**Comment by carlosperate** [comment]
Also tested it with the build server using node 0.12.4.

**Comment by carlosperate** [comment]
Ok, so it turns out that when I tried to check if this file exists:

 `.../Downloads/ardublockly.../arduexec/ardublockly/index.html`

There is a file there named: 

`.../Downloads/ardublockly.../arduexec/ardublockly`

And that is why `fs.stat` throws the "not a dir" exception, if finds the `ardublockly` file and fails when it tries to use it as a directory. Could the `exists` function be updated to catch this special case and still provide the expected output?

**Comment by szwacz** [comment]
Sure it can! But let me make sure I understand what actually happened.
You wanted to look if file `arduexec/ardublockly/index.html` exists, but it turns out there is a file `arduexec/ardublockly`, and because of that `exists` method dindn't return correct message - doesn't exist (what you expected), but crashes.
Is my understanding correct?

**Comment by carlosperate** [comment]
Yeah, that exactly it.

**Comment by szwacz** [comment]
When I thought more about your case I've started to have doubts. Ok, exists will tell you that path doesn't exist, but what then? This is still malformed path, to which you can't write (because that file earlier will throw the same error in write/mkdir case).

What you wanted to do when `exists` returns you `false` in scenario we are talking about here?

**Comment by szwacz** [comment]
I'm leaning towards throwing more meaningful error in your case, something like 'hey, this path is malformed, because x is a file, not a directory'.

**Comment by carlosperate** [comment]
I basically navigate through the path tree from the bottom to top, trying to find the `ardublockly/index.html` file within any of those folders in a loop. So, if the file does not exists in `a/b/c/ardublockly/index.html' then it moves one directory up and tries `a/b/ardublockly/index.html`.

I don't quite see the logic of throwing an informative error in this case, the way I see it, if somebody wants to now if the file `a/b/ardublockly/index.html` exists, why would they care if `a/b/ardublockly` is a file?

**Comment by szwacz** [comment]
Ok, let's give it a try.
My concern is that if file doesn't exist the next step for most people will be to try to create that file, and that operation will inevibaly throw error. But then they will see the `ENOTDIR` error so still should be fine.

**Comment by szwacz** [comment]
Version 0.6.5 should be free of this error.

**Comment by carlosperate** [comment]
Thanks Jakub.

I didn't realised that trying to create a file in this example would end up raising the same exception, in that case I guess you are still right with the fact that they'll get the same kind of exception anyway. Thanks again!
