### ISSUE TITLE
Intermittent ENOTEMPTY when calling `remove`

### ISSUE THREAD

**Issue by papb** [szwacz/fs-jetpack#80]
Unfortunately I was not able to reproduce this in a minimal example to include here, as good issues should do, but I'll try my best to describe what is going on.

### Summary

I'm using windows. I have a documentation generation script, which I run as `npm run docs`, in which I use `jetpack` everywhere with hundreds of calls to `write`, `copy`, `rename` and all that. And all of them synchronous. At the end, I call `jetpack.remove("docs_temp")` to delete a temporary folder that the script created (also with `jetpack`).

But I am getting an intermittent ENOTEMPTY error, thrown on the following line:

https://github.com/szwacz/fs-jetpack/blob/113965971eede3bb7906e47952a61eca2021cee6/lib/remove.js#L33

`Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\papb\Documents\path\to\docs_temp'`

By intermittent I mean that once every ten/twenty executions of `npm run docs`, I get that error.

### Investigation

To investigate this, first I added a script `"investigate"` to my `package.json` that simply calls `npm run docs` thirty times in a row.

First, to make sure I wasn't missing anything else, I executed `npm run investigate` several times, and all of them ended with error (so thirty calls in a row was a safe amount to ensure the intermittent error would always show up).

Then, I replaced my direct call to `jetpack.remove("docs_temp")` with the following:

```js
try {
    jetpack.remove("docs_temp");
} catch (e) {
    console.log(e);
    console.log("list:", jetpack.list("docs_temp"));
    console.log("exists:", jetpack.exists("docs_temp"));
    jetpack.remove("docs_temp");
}
```

With this change, calling `npm run investigate` did not end with error. But one of the calls logged the following:

```
Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\pabarbo\Documents\Projetos\bcr\docs_temp'
list: []
exists: dir
```

And clearly the removal was successful on the second attempt. This means that, for some reason, when `jetpack` tries to remove the folder right after removing its contents, somehow the filesystem still thinks that it's not empty, although immediately after everything behaves correctly, noticing that it is really empty.

As another investigation, instead of the above replacement, I also tried replacing `jetpack.remove("docs_temp")` with `rimraf.sync("docs_temp")`. Using rimraf also worked, none of the thirty calls generated an error. I am guessing that rimraf probably makes some retries by default.

### Suggestion

It's unfortunate that I couldn't obtain a reproducible example to post here, but regardless, I think `jetpack` should support retrying removals somehow. My issue would probably be solved if jetpack simply retried removing, at least once.

Investigating the source code, I noticed that the async version of `remove` has a `retryCount` parameter in a private function, but apparently that parameter is not revealed to the outside world by jetpack's API. Also, the sync version does not seem to have any support for that.

How about make a change so that jetpack automatically retries deleting, perhaps twice or three times, and add a parameter to the API to allow users to set the retry count they wish, for both `sync` and `async` versions of `remove`? Also, maybe the internal recursive calls do not have to be retried, only wrapping the external API call with a retry would already work.

Thank you very much.

**Comment by papb** [comment]
**EDIT:** My situation is worse than I thought - I am also getting `ENOTEMPTY` on `jetpack.dir` calls with the `{ empty: true }` option. This is because `dir` internally calls `remove`.

As a temporary workaround, especially since I don't have that much time to make a better solution, I ended up overwriting `dir` and `remove` and calling `rimraf` when applicable.

```js
const jetpack = require("fs-jetpack");
const rimraf = require("rimraf");
const originalJetpackDirSync = jetpack.dir.bind(jetpack);
jetpack.remove = path => rimraf.sync(jetpack.path(path));
jetpack.dir = function(path, criteria) {
    if (criteria && criteria.empty) jetpack.remove(path);
    return originalJetpackDirSync(path, criteria);
};
module.exports = jetpack;
```

**Comment by szwacz** [comment]
Thank you for comprehensive analysis :)
I agree with proposed solution, but are short on time right now. Would you be interested in making a PR with this fix? I promise to review it ASAP.

**Comment by papb** [comment]
@szwacz - Thanks for the reply. Unfortunately, after further testing, I figured that my situation is a bit worse. The retries, as I suggested, did fix the ENOTEMPTY error but now I started getting intermittent EPERM errors.

Upon further investigation, I noticed that:

* [rimraf](https://github.com/isaacs/rimraf) has several lines of code dedicated to circumventing EBUSY, ENOTEMPTY and EPERM especially on windows. There is even a [fixWinEPERMSync](https://github.com/isaacs/rimraf/blob/master/rimraf.js#L184) function.

* In the past, fs-jetpack used rimraf under the hood, but you replaced it with own code on 6456b951 for [a few reasons](https://github.com/szwacz/fs-jetpack/issues/47#issuecomment-290192615):

> * to have more code in direct control
>
> * to have as little third party dependencies as possible
>
> * to be able to do fs injection, so you can setup jetpack to use e.g. https://github.com/tschaub/mock-fs instead of standard one (feature I want to implement somewhere in the future)

After further thinking, I really think rimraf should come back. The main reason being that rimraf is a widely used library which has already gone through the pain of all these nasty intermittent errors in windows, and already has all the low-level code to fix all that mess. I know that you wanted to have as less dependencies as possible, but the only way to avoid that while still fixing my ENOTEMPTY/EPERM issues would be to basically rewrite rimraf itself inside fs-jetpack.

Another reason is that, even if the errors I have encountered can somehow be fixed by simpler code than just rewriting the whole rimraf into fs-jetpack, it's very possible that other errors might still be alive, and with a good chance that rimraf has already gone through them and fixed them as well. Also, since rimraf is so widely used, if new errors appear around, there's a good change the fix would come for free to fs-jetpack by simply bumping the rimraf version.

As for the fs injection, if I'm not mistaken this is still not implemented and I don't know if you still want to implement it in the future, but even if you do, surely we will agree that the main functionality working comes first. Also, using rimraf does not disallow fs injection - at worse, you could add a check and avoid rimraf only if fs injection is happening.

What do you say? Thanks again for the time to read all this :)

**Comment by szwacz** [comment]
I have no problem with reading long well-thought posts :)

I thought the fs injection will be a nice feature, wanted to implement it two times so far if I remember correctly. Both times finally gave up, first because it's hard to do this feature with test coverage, second because actually except this one request for it in github issues no one else asked it. So maybe this is cool feature on paper.

To the point - yes, the fastest and most straightforward way of fixing the issue is to reintroduce rimraf into the library.
