### ISSUE TITLE
times is missing from inspectTree options

### ISSUE THREAD

**Issue by jrobeson** [szwacz/fs-jetpack#82]
As can be seen here: https://github.com/szwacz/fs-jetpack/blob/master/lib/inspect_tree.js#L12

I commented the options validation, and it seemed to work.

Is there a reason `times` is not allowed, or was it just added yet?

**Comment by papb** [comment]
What does `times` do?

**Comment by szwacz** [comment]
I can't recall a reason why `times` shouldn't be used in that case, so almost certainly this is an oversight.

PR is welcome :)

**Comment by szwacz** [comment]
Added in version `2.3.0`
