### ISSUE TITLE
fsj->dir empties directories per default?

### ISSUE THREAD

**Issue by michapixel** [szwacz/fs-jetpack#87]
jesus christ! it completely emptied all of my gitlab-projects-directories.

**Comment by szwacz** [comment]
It doesn't: https://github.com/szwacz/fs-jetpack/blob/master/spec/dir.spec.ts#L92
If some misconfiguration of fs-jetpack led to unintended consequences please tell your story. Maybe it will be possible to add guards the the API so it won't happen again.

**Comment by papb** [comment]
I am a constant user of fs-jetpack and I've never seen this happen. And `jetpack.dir` is one of the functions I use the most. Please tell your story so we can investigate it. I can't help but think that you made some mistake.

**Comment by michapixel** [comment]
i already closed this ;)
It wasn't fsj, in fact it was a nodegit, as i was trying sth. to clone / pull dozens of projects. 
sorry for the buzz.
