### ISSUE TITLE
Make `write` accept `mode`

### ISSUE THREAD

**Issue by Weakky** [szwacz/fs-jetpack#91]
## Description

It'd be great if we could pass the native fs `mode` option to `writeFile`.

Thanks for the great work! 🙏

**Comment by szwacz** [comment]
There you have it :) Version `2.4.0`.

**Comment by Weakky** [comment]
Awesooome, thanks a ton 🙏

**Comment by papb** [comment]
What is the default mode?

**Comment by szwacz** [comment]
Operating system decides on default mode if I recall it correctly, that's why there is no default specified in the readme.
